services:
  - type: web
    name: httpfromtcp
    env: docker
    build:
      dockerfile: Dockerfile
    envVars:
      - key: PORT
        value: 8080
    plan: free  # Puedes cambiarlo a 'standard' o 'plus' seg√∫n necesites
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /
    envVarReferences:
      - env: GO_VERSION
        name: go-version
        required: true
        defaultValue: 1.21
